url: http://www.biowin.cc

title: 博文机器人

keywords: 博文机器人

description: 佛山博文机器人自动化科技有限公司成立于2014年11月，是一家致力于发展中国机器人与自动化技术和应用的新兴高科技企业。

permalink: /products/:title.html

relative_permalinks: false

exclude:
  - README.md

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - js
    - css
  js_compressor: uglifier
  css_compressor: sass
  cache: true
  cache_assets: true
  gzip: []
